name: Versions updater
on:
  push:
    branches: [master] # Trigger workflow for any push to master
  pull_request:
    branches: [ master ] # Trigger workflow for any PR targeting master
  workflow_dispatch: # Allow manual trigger
#    inputs: # Enable this for signed commit in case GPG key is updated
#      allowEmptyCommit:
#        description: 'Allow empty commit (yes/no)'
#        required: true
#        default: 'no'
  schedule:
    - cron: '42 2 * * 0' # Trigger workflow once a week


jobs:
  actives:
    name: "Update actives.json"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'php-versions-repo'
    steps:
      - name: Get current date/time
        id: datetime
        run: echo "::set-output name=value::$(date +'%Y-%m-%d')"
        working-directory: '/tmp' # Repository is not yet there => use tmp directory as working directory
      - name: "Checkout php/web-php repository"
        uses: actions/checkout@v2
        with:
          repository: 'php/web-php'
          path: 'web-php-repo'
      - name: "Add custom script"
        run: |
          echo '<?php
          include "include/branches.inc";
          echo json_encode(get_active_branches());
          ' > generate_active_version.php
          cat generate_active_version.php
        working-directory: 'web-php-repo'
      - name: "Generate active versions JSON file"
        id: active_versions
        run: |
          php generate_active_version.php
          echo "::set-output name=json::'$(php generate_active_version.php)'"
        working-directory: 'web-php-repo'
      - name: "Checkout yoanm/php-version repository"
        uses: actions/checkout@v2
        with:
          ref: '${{ github.head_ref || github.ref }}'
          path: 'php-versions-repo'
          token: '${{ secrets.PAT_COMMIT }}'
      - name: "Update actives.json file"
        run: |
          php ../web-php-repo/generate_active_version.php
          php ../web-php-repo/generate_active_version.php > actives.json
          cat actives.json
      - name: "Add / commit / push"
        run: |
          git config user.name "Yoanm"
          git config user.email "yoanm@users.noreply.github.com"
          git add actives.json
          if [ $(git diff --cached --name-only | wc -l) -gt 0 ]; then
            echo "Pushing updated file:"
            git diff --cached actives.json
            git commit -m "Update actives.json (${{ steps.datetime.outputs.value }}) \
            \
            See ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} \
            \
            ";
            git push origin;          
          else
            echo "Nothing to commit !";
          fi;
        working-directory: 'php-versions-repo'
